workflows:

  flutter_android_ios:
    name: Tasty Trove
    environment:
      flutter: stable

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Generate icons
        script: dart run flutter_launcher_icons:main

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS IPA
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build/ios/iphoneos/Runner.ipa

    publishing:
      email:
        recipients:
          - eivanphils@gmail.com

trigger:
  event:
    - push:
        branch:
          include:
            - master # Establece la rama que desencadenará el proceso de compilación/despliegue